// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BattleSubscriptionController from "./battle_subscription_controller"
application.register("battle-subscription", BattleSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)
